#' @title FaaS - updating models in forecast pack generated by scale modeling (discontinued)
#'
#' @description This way of updating a model has been discontinued. For details about
#' the new way to perform updates, see the documentation in
#' https://storage.googleapis.com/bkt-prod-4casthub/docs/model-update-api-en-us.pdf.
#'
#' @param ... advanced parameters.
#' @return A warning informing the user that this way of updating a model has been
#' discontinued
#' @rdname run_update
#' @export
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
run_update <- function(...) {

  stop(paste0("This way of updating a model has been discontinued. For details about " ,
              "the new way to perform updates, see the documentation in ",
              "https://storage.googleapis.com/bkt-prod-4casthub/docs/model-update-api-en-us.pdf."))

}


